replicaCount: 2
image:
  repository: 620057207037.dkr.ecr.ap-south-2.amazonaws.com/go-service
  tag: v1.0.4
  pullPolicy: Always
resources:
  limits:
    cpu: 200m
    memory: 256Mi
env:
  LOG_LEVEL: "info"
